# Generated by Django 5.2.3 on 2025-10-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking_place.districtname'),
        ),
    ]
