# Generated by Django 5.2.3 on 2025-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validityperiod',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
