# Generated by Django 5.2.3 on 2025-10-14 07:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0002_districtname_alter_district_district_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='districtname',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('district_name'), name='uniq_district_name_ci'),
        ),
    ]
