# Generated by Django 5.2.3 on 2025-10-14 07:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0003_districtname_uniq_district_name_ci'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cityname',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('city_name'), name='uniq_city_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='streetname',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('street_name'), name='uniq_street_name_ci'),
        ),
    ]
