# Generated by Django 5.2.3 on 2025-10-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='announcement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notice_board.announcement'),
        ),
    ]
