# Generated by Django 5.2.3 on 2025-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitation_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='announcement',
        ),
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invitation',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invitation',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
